language: swift
osx_image: xcode10.1
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)
podfile: Podfile
xcode_workspace: NAME.xcworkspace
xcode_scheme: NAME
cache:
  - bundler
  - cocoapods
before_install:
  - gem install cocoapods
  - pod repo update
branches:
  only:
    - master
